<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <meta name="keywords" content="Dating Game" />
        <meta name="description" content="" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta name="robots" content="index, follow" />
        <meta name="Revisit-After" content="7 Days" />
        <meta http-equiv="content-language" content="nl" />
        <meta http-equiv="imagetoolbar" content="no" />
        <title></title>

        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css" type="text/css" />
        <!--[publication_css]-->
        <script src="https://www.google.com/jsapi" type="text/javascript"></script>
        <script type="text/javascript">

            google.load("jquery", "1.6.2");

        </script>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
        <!--[publication_javascript]-->

        <link rel="stylesheet" href="/css/fancybox/jquery.fancybox.css?v=2.1.3" type="text/css" media="screen" />
        <script type="text/javascript" src="/js/fancybox/jquery.fancybox.pack.js?v=2.1.3"></script>
    </head>
    <body>

        <div class="body-container">
            <div class="index">
                <div class="column left">
                    <?php echo $this->content();?>
                    <br />
                    <div class="article_bottom">
                        <?php echo $this->bottom();?>
                    </div>
                </div>
                <div class="column_right">
                    <?php echo $this->sidebar();?>
                </div>
            </div>
        </div>

        <div id="footer">

        </div>
    </body>
</html>