<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Krista Game</title>
		<link type="text/css" rel="stylesheet" href="/css/style.css"  media="screen" charset="utf-8" />
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css" type="text/css" />
		
		<script type="text/javascript" src="/js/default.js"></script>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<meta name="robots" content="index, follow" />
		<meta name="Revisit-After" content="7 Days" />
		<meta http-equiv="content-language" content="nl" />
		<meta http-equiv="imagetoolbar" content="no" />
		<meta http-equiv="Content-Type" content="text/html" />
	</head>
	<body>
		
		
		<div class="screen">
			<div class="top"></div>
			<div class="content">
				<?php echo $this->content();?>
			</div>
		</div>
		
		
	</body>
</html>